# Generated by Django 2.2 on 2023-12-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone', models.CharField(choices=[('US/Hawaii', 'Hawaii Standard Time'), ('US/Alaska', 'Alaska Standard Time'), ('US/Pacific', 'Pacific Standard Time'), ('US/Mountain', 'Mountain Standard Time'), ('US/Central', 'Central Standard Time'), ('US/Eastern', 'Eastern Standard Time')], default='US/Mountain', max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')),
                ('banner', models.ImageField(default='profilebanner.jpg', upload_to='profile_banners')),
                ('followers', models.ManyToManyField(related_name='_profile_followers_+', to='user.Profile')),
                ('following', models.ManyToManyField(related_name='_profile_following_+', to='user.Profile')),
                ('likedPosts', models.ManyToManyField(related_name='likedPosts', to='feed.Post')),
                ('savedPosts', models.ManyToManyField(related_name='savedPosts', to='feed.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
